apiVersion: v1
kind: Secret
metadata:
  name: gitlab-registry-usuario
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "osfatun-frontend-usuario.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.imagePullSecret.dockerconfigjson }}
