apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "osfatun-backend.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    {{- if .Values.ingress.publicAccess }}
    ingress.pomerium.io/allow_public_unauthenticated_access: "true"
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: backend-tls
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8000
