apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-media
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "osfatun-backend.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.media.storageClass }}
  resources:
    requests:
      storage: {{ .Values.media.size }}
