apiVersion: v1
kind: Secret
metadata:
  name: gitlab-registry
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "osfatun-frontend.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.imagePullSecret.dockerconfigjson }}
